version: "3.9"
services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --skip-character-set-client-handshake


  application1:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: "market-application1"
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db

  application2:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: "market-application2"
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - application1
